export type TypographyVariant =
  | "display-1"
  | "display-2"
  | "h1"
  | "h2"
  | "h3"
  | "h4"
  | "h5"
  | "h6"
  | "subheading"
  | "body"
  | "paragraph-sm"
  | "paragraph-md"
  | "paragraph-lg"
  | "paragraph-xl"
  | "footer"
  | "caption"
  | "code";

export type TypographyComponent =
  | "p"
  | "span"
  | "div"
  | "label"
  | "h1"
  | "h2"
  | "h3"
  | "h4"
  | "h5"
  | "h6"
  | "code";

export type FontWeight =
  | "thin"
  | "extralight"
  | "light"
  | "normal"
  | "medium"
  | "semibold"
  | "bold"
  | "extrabold";

export type IconComponent =
  | "ChevronDown"
  | "ChevronLeft"
  | "ChevronRight"
  | "ChevronUp"
  | "ChevronDownDouble"
  | "ChevronLeftDouble"
  | "ChevronRightDouble"
  | "ChevronUpDouble"
  | "SwitchHorizontal"
  | "BarChartSquare"
  | "Data"
  | "DataFlow"
  | "CryptoCurrency"
  | "Heart"
  | "LogIn"
  | "SearchLg"
  | "Settings"
  | "Image"
  | "LayersThree"
  | "Cube"
  | "Flag"
  | "MarkerPin"
  | "Users";

export type ColorType =
  | "volt"
  | "voltDark"
  | "azule"
  | "azuleDark"
  | "lobster"
  | "lobsterDark"
  | "sand"
  | "sandDark"
  | "tulip"
  | "tulipDark"
  | "green"
  | "greenDark"
  | "black"
  | "white"
  | "gray-1"
  | "gray-2"
  | "gray-3"
  | "gray-4"
  | "gray-5"
  | "gray-6"
  | "gray-7"
  | "gray-8"
  | "inherit";
