import type { Config } from "tailwindcss";
import {
  borderRadius,
  borderWidth,
  colors,
  fontSize,
  fontWeight,
  spacing,
  screens,
  display,
  percentages,
  cursor,
} from "./tailwind-classes";


const getKeyMap = (obj, prefix) => {
  return [
    ...Object.keys(obj).map((key) => `${prefix}-${key}`),
    ...Object.keys(obj).map((key) => `tablet:${prefix}-${key}`),
    ...Object.keys(obj).map((key) => `desktop:${prefix}-${key}`),
    ...Object.keys(obj).map((key) => `hover:${prefix}-${key}`),
    ...Object.keys(obj).map((key) => `focus:${prefix}-${key}`),
  ];
};
const getKeyOnlyMap = (obj) => {
  return [
    ...Object.keys(obj).map((key) => key),
    ...Object.keys(obj).map((key) => `tablet:${key}`),
    ...Object.keys(obj).map((key) => `desktop:${key}`),
  ];
};

const numberList = {
  px: 0,
  0: 0,
  0.5: 0,
  1: 0,
  1.5: 0,
  2: 0,
  2.5: 0,
  3: 0,
  3.5: 0,
  4: 0,
  5: 0,
  6: 0,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  14: 0,
  16: 0,
  20: 0,
  24: 0,
  28: 0,
  32: 0,
  36: 0,
  40: 0,
  44: 0,
  48: 0,
  52: 0,
  56: 0,
  60: 0,
  64: 0,
  72: 0,
  80: 0,
  96: 0,
  auto: "auto",
  none: "none",
};

// We want each package to be responsible for its own content.
const config: Omit<Config, "content"> = {
  safelist: [
    ...getKeyMap(colors, "text"),
    ...getKeyMap(colors, "bg"),
    ...getKeyMap(colors, "border"),
    ...getKeyMap(borderWidth, "border"),
    ...getKeyMap(borderRadius, "rounded"),
    ...getKeyMap(fontSize, "text"),
    ...getKeyMap(fontWeight, "font"),
    ...getKeyMap(numberList, "h"),
    ...getKeyMap(numberList, "inset"),
    ...getKeyMap(numberList, "min-h"),
    ...getKeyMap(numberList, "max-h"),
    ...getKeyMap(numberList, "w"),
    ...getKeyMap(numberList, "min-w"),
    ...getKeyMap(numberList, "max-w"),
    ...getKeyMap(numberList, "m"),
    ...getKeyMap(spacing, "m"),
    ...getKeyMap(numberList, "mr"),
    ...getKeyMap(spacing, "mr"),
    ...getKeyMap(numberList, "my"),
    ...getKeyMap(spacing, "my"),
    ...getKeyMap(numberList, "mx"),
    ...getKeyMap(spacing, "mx"),
    ...getKeyMap(numberList, "mb"),
    ...getKeyMap(spacing, "mb"),
    ...getKeyMap(numberList, "mt"),
    ...getKeyMap(spacing, "mt"),
    ...getKeyMap(numberList, "ml"),
    ...getKeyMap(spacing, "ml"),
    ...getKeyMap(numberList, "mr"),
    ...getKeyMap(spacing, "mr"),
    ...getKeyMap(numberList, "p"),
    ...getKeyMap(spacing, "p"),
    ...getKeyMap(numberList, "px"),
    ...getKeyMap(spacing, "px"),
    ...getKeyMap(numberList, "py"),
    ...getKeyMap(spacing, "py"),
    ...getKeyMap(numberList, "pb"),
    ...getKeyMap(spacing, "pb"),
    ...getKeyMap(numberList, "pt"),
    ...getKeyMap(spacing, "pt"),
    ...getKeyMap(numberList, "pr"),
    ...getKeyMap(spacing, "pr"),
    ...getKeyMap(numberList, "pl"),
    ...getKeyMap(spacing, "pl"),
    ...getKeyMap(numberList, "gap"),
    ...getKeyMap(spacing, "gap"),
    ...getKeyMap(percentages, "grayscale"),
    ...getKeyMap(percentages, "brightness"),
    ...getKeyMap(cursor, "cursor"),
    ...getKeyOnlyMap(display),
  ],
  theme: {
    extend: {
      spacing,
      fontSize,
      screens,
      grayscale: percentages,
      brightness: percentages,
    },
    fontFamily: {
      sans: ["Utendo", "Inter", "Verdana", "sans-serif"],
      body: ["Utendo", "Inter", "Verdana", "sans-serif"],
      mono: ["monospace"],
    },
    fontWeight,
    colors,
    borderWidth,
    borderRadius,
    cursor,
  },
  plugins: [],
};
export default config;
